name: Tests

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0
        with:
          version: nightly

      - name: Install dependencies
        run: forge build

      - name: Clean Utility Files
        run: |
          rm -rf \
            script/*

      - name: Run coverage
        run: |
          forge coverage >> cov.dat
          echo $(cat cov.dat | grep -E "\% \(|\-\-\|\-\-|\| \%") >> cov_regexp.dat
      - name: Refactoring
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "| |"
          replace: "|\\n|"
          regex: false
          include: "**cov_regexp.dat"

      - name: Fetching Coverage Results
        id: coverage
        run: echo COVERAGE=$(cat cov_regexp.dat) >> "${GITHUB_OUTPUT}"

      - name: Collapse previous comments
        uses: kanga333/comment-hider@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment to Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ steps.coverage.outputs.COVERAGE }}`
            })
